<div class="container mx-auto px-4 py-8">
<div class="flex justify-between items-center">
                <h1 class="text-2xl font-bold text-gray-800">Lista de Tareas</h1>
                <div class="flex space-x-4">
                    <a href="<?= $this->baseUrl() ?>/tasks/create" class="bg-green-700 hover:bg-green-500 text-white hover:text-black font-bold px-4 py-2 rounded-full mb-1 border-b-2 border-transparent hover:border-white">Nueva Tarea</a>
                </div>
            </div>
    
    <div class="bg-[rgba(255,255,255,0.5)] p-4 shadow-md rounded-lg overflow-hidden">
        <table class="min-w-full leading-normal">
            <thead>
                <tr>
                    <th class="px-5 py-3 border-b-2 border-gray-200 text-center text-base font-bold uppercase tracking-wider">
                        Title
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 text-center text-base font-bold uppercase tracking-wider">
                        User
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 text-center text-base font-bold uppercase tracking-wider">
                        Status
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 text-center text-base font-bold uppercase tracking-wider">
                        Start Time
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 text-center text-base font-bold uppercase tracking-wider">
                        View
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->tasks as $task): ?>
                <tr>
                    <!-- <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                        <?= $task->id ?>
                    </td> -->
                    <td class="px-5 py-5 border-b border-gray-200 text-center text-sm">
                                <p class="whitespace-no-wrap">
                                    <?= $task->title ?>
                                </p>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 text-center text-sm">
                        <p class="whitespace-no-wrap"><?= $task->user ?></p>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 text-center text-sm">
                        <span class="relative inline-block px-3 py-1 font-semibold rounded-full 
                            <?php 
                            switch($task->status) {
                                case 'pending':
                                    echo 'text-yellow-900 bg-yellow-200';
                                    break;
                                case 'in_progress':
                                    echo 'text-blue-900 bg-blue-200';
                                    break;
                                case 'done':
                                    echo 'text-green-900 bg-green-200';
                                    break;
                                default:
                                    echo 'text-gray-900 bg-gray-200';
                            }
                            ?>">
                            <?= ucfirst(str_replace('_', ' ', $task->status)) ?>
                        </span>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 text-center text-sm">
                        <p class="whitespace-no-wrap">
                            <?= $task->startTime ?>
                        </p>
                    </td>
                    <td class="px-5 py-5 border-b border-gray-200 text-center text-sm">
                    <a href="<?= $this->baseUrl() ?>/tasks/view/id/<?= $task->id ?>" class="hover:text-green-800 hover:underline hover:decoration-green-800 decoration-2">🔍View</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
